# docker-compose.yml for NetworkMapper v2
# ©AngelaMos | ©CertGames.com


services:
  networkmapper:
    build:
      context: .
      dockerfile: ops/Dockerfile
    image: mapper:latest    
    network_mode: "host"   
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./output:/app/output
      - ./scripts/host-open.sh:/usr/local/bin/host-open
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - DOCKER_HOST_BROWSER=1
      - HOST_PROJECT_PATH=${PWD}
            
#
#     0000             0000        7777777777777777/========___________
#   00000000         00000000      7777^^^^^^^7777/ || ||   ___________
#  000    000       000    000     777       7777/=========//
# 000      000     000      000             7777// ((     //
#0000      0000   0000      0000           7777//   \\   //
#0000      0000   0000      0000          7777//========//
#0000      0000   0000      0000         7777
#0000      0000   0000      0000        7777
# 000      000     000      000        7777
#  000    000       000    000       77777
#   00000000         00000000       7777777
#     0000             0000        777777777      
